import { jsPDF } from 'jspdf'

import type { MedicalRecord, Vaccination } from '@/services/medical'

export type PdfAction = 'download' | 'view' | 'print'

export interface AdoptionCertificateData {
  petName: string
  breed: string
  age: string
  adopterName: string
  shelterName: string
  adoptionDate: string
  petImageUrl?: string | null
  certificateNumber?: string
}

const BRAND_GREEN = '#16A34A'
const TEXT_DARK = '#111827'
const TEXT_MUTED = '#6B7280'

function formatDate(value: string | null | undefined) {
  if (!value) return '—'
  return new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(
    new Date(value),
  )
}

function slugify(value: string) {
  return value.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')
}

function drawBrandedHeader(doc: jsPDF, subtitle: string) {
  doc.setFillColor(BRAND_GREEN)
  doc.rect(0, 0, 210, 26, 'fill')
  doc.setTextColor('#FFFFFF')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text('PawSphere', 16, 13)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(subtitle, 16, 20)
  doc.text('pawsphere.bd', 194, 20, { align: 'right' })
}

function drawFooter(doc: jsPDF) {
  doc.setDrawColor('#E5E7EB')
  doc.line(16, 275, 194, 275)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(TEXT_MUTED)
  doc.text(
    `Generated by PawSphere on ${formatDate(new Date().toISOString())}`,
    16,
    281,
  )
}

function drawFieldRows(
  doc: jsPDF,
  startY: number,
  rows: [string, string][],
): number {
  let y = startY
  rows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(TEXT_MUTED)
    doc.text(label.toUpperCase(), 16, y)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(TEXT_DARK)
    const lines = doc.splitTextToSize(value || '—', 178) as string[]
    doc.text(lines, 16, y + 6)
    y += 12 + (lines.length - 1) * 5.5
  })
  return y
}

function deliverPdf(doc: jsPDF, filename: string, action: PdfAction = 'download') {
  if (action === 'download') {
    doc.save(filename)
    return
  }

  const blobUrl = doc.output('bloburl')
  if (action === 'view') {
    window.open(blobUrl, '_blank', 'noopener,noreferrer')
    return
  }

  const printWindow = window.open(blobUrl, '_blank', 'noopener,noreferrer')
  if (!printWindow) {
    doc.save(filename)
    return
  }
  printWindow.addEventListener('load', () => {
    printWindow.focus()
    printWindow.print()
  })
}

async function loadImageDataUrl(url: string): Promise<string | null> {
  try {
    const response = await fetch(url)
    if (!response.ok) return null
    const blob = await response.blob()
    return await new Promise((resolve) => {
      const reader = new FileReader()
      reader.onload = () => resolve(String(reader.result))
      reader.onerror = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

export async function generateAdoptionCertificatePDF(
  data: AdoptionCertificateData,
  action: PdfAction = 'download',
): Promise<void> {
  const doc = new jsPDF()
  drawBrandedHeader(doc, 'Official Adoption Certificate')

  doc.setDrawColor(BRAND_GREEN)
  doc.setLineWidth(0.6)
  doc.roundedRect(14, 34, 182, 230, 4, 4)

  doc.setTextColor(BRAND_GREEN)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('Certificate of Adoption', 105, 50, { align: 'center' })

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(TEXT_MUTED)
  doc.text('This certifies that the following companion has found a forever home.', 105, 58, {
    align: 'center',
  })

  let contentTop = 68
  if (data.petImageUrl) {
    const imageData = await loadImageDataUrl(data.petImageUrl)
    if (imageData) {
      try {
        const format = imageData.includes('image/png') ? 'PNG' : 'JPEG'
        doc.addImage(imageData, format, 80, contentTop, 50, 50)
        contentTop = 126
      } catch {
        contentTop = 68
      }
    }
  }

  doc.setTextColor(TEXT_DARK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text(data.petName, 105, contentTop, { align: 'center' })

  drawFieldRows(doc, contentTop + 12, [
    ['Breed', data.breed || '—'],
    ['Age', data.age || '—'],
    ['Adopted by', data.adopterName],
    ['Shelter', data.shelterName],
    ['Adoption date', formatDate(data.adoptionDate)],
    [
      'Certificate no.',
      data.certificateNumber ||
        `PSC-${new Date(data.adoptionDate || Date.now()).getFullYear()}-${slugify(data.petName).slice(0, 8).toUpperCase()}`,
    ],
  ])

  const signatureY = 230
  doc.setDrawColor('#D1D5DB')
  doc.line(28, signatureY, 88, signatureY)
  doc.line(122, signatureY, 182, signatureY)
  doc.setFontSize(9)
  doc.setTextColor(TEXT_MUTED)
  doc.text('Shelter Representative', 58, signatureY + 6, { align: 'center' })
  doc.text('Adopter Signature', 152, signatureY + 6, { align: 'center' })

  doc.setFontSize(8)
  doc.text('PawSphere · Helping every pet find a loving home', 105, 255, {
    align: 'center',
  })

  drawFooter(doc)
  deliverPdf(doc, `pawsphere-adoption-${slugify(data.petName)}.pdf`, action)
}

export function generatePrescriptionPDF(
  record: MedicalRecord,
  action: PdfAction = 'download',
): void {
  const doc = new jsPDF()
  drawBrandedHeader(doc, 'Veterinary Prescription')

  doc.setTextColor(TEXT_DARK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text(`Prescription for ${record.pet_name}`, 16, 40)

  drawFieldRows(doc, 52, [
    ['Veterinarian', record.vet_name],
    ['Clinic', record.clinic_name],
    ['Owner', record.owner_name],
    ['Pet', record.pet_name],
    ['Diagnosis', record.diagnosis],
    ['Medicines / dosage', record.prescription],
    ['Follow-up date', formatDate(record.follow_up_date)],
    ['Date issued', formatDate(record.created_at)],
  ])

  drawFooter(doc)
  deliverPdf(doc, `pawsphere-prescription-${slugify(record.pet_name)}.pdf`, action)
}

export function generateVaccinationPDF(
  vaccinations: Vaccination[],
  petName?: string,
  action: PdfAction = 'download',
): void {
  if (vaccinations.length === 0) {
    throw new Error('There are no vaccination records to export.')
  }

  const doc = new jsPDF()
  drawBrandedHeader(doc, 'Vaccination Record')

  const title = petName
    ? `Vaccination record for ${petName}`
    : 'Vaccination record'
  doc.setTextColor(TEXT_DARK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.text(title, 16, 40)

  const ownerName = vaccinations[0]?.owner_name
  if (ownerName) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(TEXT_MUTED)
    doc.text(`Owner: ${ownerName}`, 16, 48)
  }

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(TEXT_MUTED)
  const columns: [string, number][] = [
    ['VACCINE', 16],
    ['PET', 58],
    ['GIVEN', 90],
    ['NEXT DUE', 120],
    ['VETERINARIAN', 152],
  ]
  columns.forEach(([label, x]) => doc.text(label, x, 58))
  doc.setDrawColor('#E5E7EB')
  doc.line(16, 61, 194, 61)

  let y = 68
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(TEXT_DARK)

  vaccinations.forEach((vaccination) => {
    if (y > 265) {
      doc.addPage()
      drawBrandedHeader(doc, 'Vaccination Record')
      y = 40
    }
    doc.text(vaccination.vaccine_name.slice(0, 20), 16, y)
    doc.text(vaccination.pet_name.slice(0, 12), 58, y)
    doc.text(formatDate(vaccination.vaccination_date), 90, y)
    doc.text(formatDate(vaccination.next_due_date), 120, y)
    doc.text((vaccination.veterinarian_name || '—').slice(0, 20), 152, y)
    y += 8
  })

  drawFooter(doc)
  deliverPdf(
    doc,
    `pawsphere-vaccinations-${slugify(petName ?? 'all')}.pdf`,
    action,
  )
}
